first = input("First Name: ")
last = input("Last Name: ")
email = input("Email Adres: ")
phone = input("Phone number: ")
job_title = input ("Job Title: ")
id = input("Id Number: ")

print("\n The Id Card is: ")
print("-----------------------------------")
print(f"{last.upper()} {first.capitalize()}")
print(job_title.capitalize())
print(f"ID: {id}")
print()
print(email.lower())
print(phone)
print("-----------------------------------")